global:
  scrape_interval: 15s  # How often to scrape metrics

scrape_configs:
  - job_name: 'django_app'
    static_configs:
      - targets: ['django:8000']  # Use the service name if using Docker Compose